<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>All_Test_Cases_of_Counts</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>6e02937d-0ba3-45ac-80db-957af1b12739</testSuiteGuid>
   <testCaseLink>
      <guid>ccdec1a9-e557-4391-8384-c0d3c481e625</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_BO_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a56acae-3aa7-460c-8798-af5242499afa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48e44a49-2ace-4aad-b3a6-9bac466079ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_BO_Column_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4baa237-7f84-437f-be39-726eba229e09</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ec929609-ef64-4630-a962-eeae73cd699d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_SRC_Trust_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f54c6ebc-9f0c-411a-8544-2e4036484e13</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a45ebf2-e7f2-4ea0-956f-5f7d1a3c686d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_BO_QUERY_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18471e39-17f7-4c72-b843-a00509d57e39</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5baf65a3-c8c3-43f4-a624-947ebb5253b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_BO_QUERY_GRP_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbc9a853-060e-4424-9cbf-57f8e0325e50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b8fbbab-7331-4b6c-9698-6e6b71494665</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_BO_SQL_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2697dc6-42fc-4cc9-86eb-f4e99e8ef92a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b28e4d4c-b599-4ba9-9789-87572cc87bd7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_Landing_Col_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>060db90e-54d6-4302-865c-88a4b20942b0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83201521-c382-40d4-88df-6d593b0c4bcb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_Landing_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b35996b-da93-4a15-9d2b-4cc38e8f00c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9332bcb-7d8c-4ba2-aeab-532398a27e47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_STG_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5059c00d-2341-4942-9761-5207a124c556</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b7f8dee8-0b63-4d80-9cac-73a59ac68589</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_STG_Col_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f127a18f-8594-4d85-a7b5-bb57abc52afd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a76e229c-709f-4be7-bad2-039a39fa72f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_MTCH_COL_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d2ee91d-b70b-4a6c-a150-18c17b5e1b58</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7633b45b-8689-411a-9240-46910a7bf978</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_MTCH_FUZZY_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c2c0dab-9b7d-46c7-99e3-119ea6be4faa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f4a3e645-2c78-4f57-97c2-222001fa677d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_MTCH_PATH_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffb730c1-352b-49ff-87dd-cc71a4975eb8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f2027338-bd87-4e67-81f8-b4972bdf6de4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_PCKG_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d47955bc-5e6a-41c6-8cf1-5f5a9269fadb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff65adff-6a30-4df1-98d3-7b854457f586</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_SRC_System_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>699aa444-0039-4fe2-a732-fc528c16419d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22fa27d4-7d0f-4e72-a730-75280f945f10</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Check_BG_Count</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9180cbf2-a8a8-438a-8726-60748b23c507</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
